server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    #registerWithEureka表示是否注册自身到eureka服务器,因为当前这个应用就是eureka服务器，没必要注册自身
    registerWithEureka: false
    #fetchRegistry表示是否从eureka服务器获取注册信息
    fetch-registry: false
    #设置eureka服务器所在的地址，查询服务和注册服务都需要依赖这个地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server

